import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin :learning layout in next js",
  description: "Generated by create next app",
};

export default function adminLayout({ children }) {
  return (
    <>
      <spna>Admin Navbar</spna>
      {children}
    </>
  );
}
